a = float(input("a="))
b = float(input("b="))
c = float(input("c="))
d = float(input("d="))
e = float(input("e="))
f = float(input("f="))
y = ((f * a - e * c) / (d * a - b * c))
x = ((e - b * y) / a)
print(x, y)
